name: read secret
on:
  push:
    branches: [ "main" ]
jobs:
  secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3               
  
      - name: Set up Kubernetes
        uses: azure/k8s-set-context@v1
      
      - name: List Secret
        run: |
          echo "ns from new secret"
          kubectl get ns   --kubeconfig ${{ secrets.KUBECONFIG }} 
        
