name: read secret
on:
  push:
    branches: [ "main" ]
jobs:
  secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up kubectl
        env: # Or as an environment variable
          config: ${{ secrets.TEST }}  
        run: kubectl get namespaces --kubeconfig config
        
