name: read secret
on:
  push:
    branches: [ "main" ]
jobs:
  secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up kubectl
        run: |
          echo "${{ secrets.TEST }}" | base64 -d > kubeconfig.yaml
          mkdir -p ~/.kube
          mv kubeconfig.yaml ~/.kube/config

      - name: List Namespaces
        run: kubectl get namespaces 
        
