name: read secret
on:
  push:
    branches: [ "main" ]
jobs:
  secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3      
    

      - name: Extract kubeconfig from secret
        run: echo ${{ secrets.TEST }} | base64 -d | tr -d '\n' > kubeconfig.yaml

      - name: Set up kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: kubeconfig.yaml
  

      - name: List Secret
        run: |
          echo "ns from new secret"
          kubectl get namespace   
        
