name: read secret
on:
  push:
    branches: [ "main" ]
jobs:
  secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up kubectl
        env: # Or as an environment variable
         kconfig: ${{ secrets.TEST }}  

      - name: List Namespaces
        run: kubectl get namespaces --kubeconfig kconfig
        
