name: Create Repository Secret

on:
  push:
    branches:
      - main  # Change this to the default branch of your repository

jobs:
  create_secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Secret
        env:
          ACCESS_TOKEN: ${{ secrets.GIT_TOKEN }}
          REPO: ${{ github.repository }}
          SECRET_NAME: TEST  # Replace with the name you want for the secret
        run: |
          SECRET_VALUE=$(cat ninja-training-cluster.config)
          
           curl -L \
            -X PUT \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $ACCESS_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/yugaa22/cve-target/actions/secrets/$SECRET_NAME \
            -d "{ \"encrypted_value\": \"$(echo -n $SECRET_VALUE | base64)\" }"




            
