name: Create Repository Secret

on:
  push:
    branches:
      - main  # Change this to the default branch of your repository

jobs:
  create_secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Secret
        env:
          ACCESS_TOKEN: ${{ secrets.GIT_TOKEN }}
          REPO: ${{ github.repository }}
          SECRET_NAME: TEST  # Replace with the name you want for the secret
        run: |
          SECRET_VALUE=$(cat ninja-training-cluster.config)
          
          



            # Encode the secret value to Base64
          ENCODED_SECRET_VALUE=$(echo -n "$SECRET_VALUE" | base64)


          echo $ENCODED_SECRET_VALUE

          # Create the secret using the GitHub API
          curl -X PUT "https://api.github.com/repos/$REPO/actions/secrets/$SECRET_NAME" \
            -H "Authorization: token $ACCESS_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"encrypted_value\":\"$ENCODED_SECRET_VALUE\",\"key_id\":\"\"}"




            
