name: Create Repository Secret

on:
  push:
    branches:
      - main  # Change this to the default branch of your repository

jobs:
  create_secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Secret
        env:
          ACCESS_TOKEN: ${{ secrets.GIT_TOKEN }}
          REPO: ${{ github.repository }}
          SECRET_NAME: TEST  # Replace with the name you want for the secret
          GITHUB_USERNAME: "yugaa22"
          GITHUB_REPO: "cve-target"
          LOCAL_FILE_PATH: "ninja-training-cluster.config"
        run: |

             # Base64 encode the content of the local file
             # KUBECONFIG_CONTENT=$(cat ninja-training-cluster.config | base64)
             #KUBECONFIG_CONTENT=$(base64 < $LOCAL_FILE_PATH | tr -d '\n')

              # Fetch the public key for the repository
              RESPONSE=$(curl -X GET -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${ACCESS_TOKEN}" "https://api.github.com/repos/${GITHUB_USERNAME}/${GITHUB_REPO}/actions/secrets/public-key")
              
              # Extract the key_id and key from the response
              KEY_ID=$(echo "$RESPONSE" | jq -r '.key_id')
              #KEY=$(echo "$RESPONSE" | jq -r '.key')

              curl -X PUT "https://api.github.com/repos/${GITHUB_USERNAME}/${GITHUB_REPO}/actions/secrets/${SECRET_NAME}"   -H "Authorization: token ${ACCESS_TOKEN}"   -H "Accept: application/vnd.github.v3+json"   -d "{\"encrypted_value\": \"${KUBECONFIG_CONTENT}\",\"key_id\": \"${KEY_ID}\"}"





            
